### ISSUE TITLE
Support showing files from multiple windows

### ISSUE THREAD

**Issue by myfairsyer** [qiray/SublimeOpenedFiles#1]
I came accross your plugin searching for sth similar to Chrome's `Sidewise Tree Style Tab` extension.
So I'd actually like to be able to see all my open files from all the windows - grouped by window.

**Comment by qiray** [comment]
OK. So show all files from all windows in one tab?

**Comment by myfairsyer** [comment]
Yes, in one list in one tab and grouped by window (as you can now group by parent directory).
If it makes more sense to have that tab with that list as in a narrow pane (as it seems to be now) in each window or if it is feasible to have it in an own, narrow window (as it's the case with `sidewise`) is another question.

TBH As this is the feature I would use `SublimeOpenedFiles` for and as it's not yet supported I haven't used it yet.
Is reordering tabs currently possible?
If not: Do you consider it something hard to implement (and/or out of scope for `SublimeOpenedFiles`)?

Thank you very much for considering this

**Comment by qiray** [comment]
Well, I'll try to add this feature when I have free time.

**Comment by qiray** [comment]
@myfairsyer, just released version 0.9.7 with adding multiple windows support. It will be available soon at packagecontrol.
